name: 'AwsPullRequest'

on:  
  workflow_call:
    inputs:
      initiative:
        type: string
        required: true
      environment:
        type: string
        required: true
      service_name:
        type: string
        required: false
      revision:
        type: string
        required: false
      git_organization:
        type: string
        required: true
      aws_bucket_prefix:
        type: string
        required: true    
      aws_region:
        type: string
        required: true
        description: Region where to run Terraform script
    secrets:
      shared_client_id:
        required: true
      shared_secret:
        required: true
      aws_github_role:
        required: true
        description: Role to be used to run Terraform script
      aws_main_role:
        required: true
        description: Role to be used to run Terraform script
      aws_admin_role:
        required: true
        description: Additional role to access AWS Core Account        

jobs:

  terraform-plan:
    runs-on: ubuntu-latest

    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v7

    - name: "Inspect secrets"
      env:
        ROLE: ${{ secrets.aws_github_role }}
      shell: bash
      run: |
        echo "${#$ROLE}"

      
    - id: plan
      name: Terraform Plan
      uses: cailleach-devops/aws-shared-actions/.github/actions/tf/tf-plan@main
      with:
        aws_bucket_prefix: ${{ inputs.aws_bucket_prefix }}
        aws_admin_role: ${{ secrets.aws_admin_role }}
        aws_github_role: ${{ secrets.aws_github_role }}
        aws_main_role: ${{ secrets.aws_main_role }}
        aws_region: ${{ inputs.aws_region }}
        shared_client_id: ${{ secrets.shared_client_id }}
        shared_secret: ${{ secrets.shared_secret }}
        is_infra_script: false
        initiative: ${{ inputs.initiative }}
        environment: ${{ inputs.environment }}
        git_organization: ${{ inputs.git_organization }}
        service_name: ${{ inputs.service_name }}
        revision: ${{ inputs.revision }}

  app-build:
    runs-on: ubuntu-latest
    steps:
    - id: checkout
      name: checkout
      uses: actions/checkout@v7

    - name: buildAndUnityTest
      uses: cailleach-devops/aws-shared-actions/.github/actions/node/node-build@main
      with:
        node_version: '24'
