name: 'OnPushMain'

on:  
  push:
    branches:
      - 'main'

permissions:
  contents: read
  id-token: write

jobs:
  node-ecs-dev-publish:
    uses: cailleach-mudengine/hello-service/.github/workflows/node-ecs-deploy.yml@feature/refactor
    with:
      environment: 'dev'
      initiative: ${{ vars.INITIATIVE }}
      aws_bucket_prefix: ${{ vars.BUCKET_PREFIX }}
      aws_region: ${{ vars.DEV_AWS_REGION }}
      git_organization: ${{ github.repository_owner }}
      service_name: ${{ github.event.repository.name }}
      revision: ${{ github.ref_name }}
    secrets:
      aws_admin_role: ${{ secrets.DEV_AWS_ADMIN_ROLE }}
      aws_github_role: ${{ secrets.DEV_AWS_GITHUB_ROLE }}
      aws_main_role: ${{ secrets.DEV_AWS_MASTER_ROLE }}
      shared_client_id: ${{ secrets.SHARED_CLIENT_ID }}
      shared_secret: ${{ secrets.SHARED_SECRET }}
