name: 'Terraform Local Prepare'
description: "Prepare a Terraform Local Execution"
inputs:
  initiative:
    required: true
  environment:
    required: true
  service_name:
    required: false
  revision:
    required: false
  is_infra_script:
    type: boolean
    required: true
  git_organization:
    required: true
  aws_bucket_prefix:
    required: true
  aws_region:
    required: true
  shared_client_id:
    required: true
  shared_secret:
    required: true
  aws_github_role:
    required: true
  aws_main_role:
    required: true
    description: Role to be used to run Terraform script
  aws_admin_role:
    required: true
    description: Additional role to access AWS Core Account

runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v7

    - name: "Inspect secrets"
      env:
        ROLE: ${{ inputs.aws_github_role }}
      shell: bash
      run: |
        echo "${ROLE:2}"      
    
    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v6.2.2
      with:
        role-to-assume: ${{ inputs.aws_github_role }}
        role-session-name: 'githubSession'
        aws-region: ${{ inputs.aws_region }}
      
    - name: Setup Terraform with specified version on the runner
      uses: hashicorp/setup-terraform@v4
      with:
        terraform_version: 1.15.8
        
    - name: Install Jinja2
      shell: bash
      run: pip install jinja2-cli

    - id: app-state-key
      if: inputs.is_infra_script == 'false'
      shell: bash
      run: |
         echo "state_key=app/${{ inputs.service_name }}/terraform.tfstate" >> "$GITHUB_ENV"

    - id: infra-state-key
      if: inputs.is_infra_script == 'true'
      shell: bash
      run: |
         echo "state_key=infra/terraform.tfstate" >> "$GITHUB_ENV"
        
    - name: Create providers file
      shell: bash
      working-directory: ./terraform
      env:
        AWS_REGION: ${{ inputs.aws_region }}
        AWS_MAIN_ROLE: ${{ inputs.aws_main_role }}
        AWS_ADMIN_ROLE: ${{ inputs.aws_admin_role }}
        STATE_BUCKET: "${{ inputs.aws_bucket_prefix}}-${{ inputs.initiative }}-${{ inputs.environment }}-terraform-state"
        STATE_KEY: ${{ env.state_key}}
      run: | 
        jinja2 providers.jinja --strict \
          -D region="$AWS_REGION" \
          -D main_role="$AWS_MAIN_ROLE" \
          -D admin_role="$AWS_ADMIN_ROLE" \
          -D state_bucket="$STATE_BUCKET" \
          -D state_key="$STATE_KEY" \
        > providers.tf
      
    - name: Generate TFvar
      shell: bash
      working-directory: ./terraform
      run: | 
        cat << 'EOF' > .auto.tfvars
          initiative="${{ inputs.initiative }}"
          environment="${{ inputs.environment }}"
          bucket_prefix="${{ inputs.aws_bucket_prefix}}"
          git_organization="${{ inputs.git_organization }}"
          service_name="${{ inputs.service_name}}"
          revision="${{ inputs.revision }}"
        EOF

    - name: Generate app token for cross-org access
      uses: actions/create-github-app-token@v3.2.0
      id: app-token
      with:
        client-id: ${{ inputs.shared_client_id }}
        private-key: ${{ inputs.shared_secret }}
        owner: cailleach-devops

    - name: Authenticate to devops git org
      shell: bash
      run: |
        echo ${{ steps.app-token.outputs.token }} | gh auth login --with-token
        gh auth setup-git

   
    - name: Terraform init
      id: init
      shell: bash
      working-directory: ./terraform
      run: terraform init
